#define VERSION_MAJOR 1
#define VERSION_MINOR 2
#define VERSION_BUILD 0
#define VERSION_REVISION 3

// Helper macro for stringification  
#define STRINGIFY(x) #x  
#define TOSTRING(x) STRINGIFY(x)  

// Corrected macro definitions  
#define VER_FILE_VERSION VERSION_MAJOR,VERSION_MINOR,VERSION_BUILD,VERSION_REVISION
#define VER_FILE_VERSION_STR TOSTRING(VERSION_MAJOR) "." TOSTRING(VERSION_MINOR) "." TOSTRING(VERSION_BUILD) "." TOSTRING(VERSION_REVISION)  
#define VER_PRODUCT_VERSION_STR VER_FILE_VERSION_STR
#define VER_PRODUCT_VERSION VER_FILE_VERSION
#define VER_PRODUCT_VERSION_STR VER_FILE_VERSION_STR
#define VER_COPYRIGHT "Copyright (C) 2025 Elizabeth Greene elizabeth.a.greene@gmail.com"



